rebol []

do %../../framework/libraries/rebgui.r
print ""

; grid scroller issue

lo: [
	g: grid #HW 606x600 data [
		header 			["Input Column" "Values" "Column Type"]
		content 		[
			["a" 1 "Unknown"]
			["b" 2 "Test"]
			["c" 3 "Master"]
			["d" 4 "Price"]
			["e" 5 "Unknown"]
			["f" 6 "Driver"]
			["g" 7 "Quantity"]
			["a" 1 "Unknown"]
			["b" 2 "Test"]
			["c" 3 "Master"]
			["d" 4 "Price"]
			["e" 5 "Unknown"]
			["f" 6 "Driver"]
			["g" 7 "Quantity"]
			["a" 1 "Unknown"]
			["b" 2 "Test"]
			["c" 3 "Master"]
			["d" 4 "Price"]
			["e" 5 "Unknown"]
			["f" 6 "Driver"]
			["g" 7 "Quantity"]
			["a" 1 "Unknown"]
			["b" 2 "Test"]
			["c" 3 "Master"]
			["d" 4 "Price"]
			["e" 5 "Unknown"]
			["f" 6 "Driver"]
			["g" 7 "Quantity"]
			["a" 1 "Unknown"]
			["b" 2 "Test"]
			["c" 3 "Master"]
			["d" 4 "Price"]
			["e" 5 "Unknown"]
			["f" 6 "Driver"]
			["g" 7 "Quantity"]
			["a" 1 "Unknown"]
			["b" 2 "Test"]
			["c" 3 "Master"]
			["d" 4 "Price"]
			["e" 5 "Unknown"]
			["f" 6 "Driver"]
			["g" 7 "Quantity"]
			["a" 1 "Unknown"]
			["b" 2 "Test"]
			["c" 3 "Master"]
			["d" 4 "Price"]
			["e" 5 "Unknown"]
			["f" 6 "Driver"]
			["g" 7 "Quantity"]
			["a" 1 "Unknown"]
			["b" 2 "Test"]
			["c" 3 "Master"]
			["d" 4 "Price"]
			["e" 5 "Unknown"]
			["f" 6 "Driver"]
			["g" 7 "Quantity"]
			["a" 1 "Unknown"]
			["b" 2 "Test"]
			["c" 3 "Master"]
			["d" 4 "Price"]
			["e" 5 "Unknown"]
			["f" 6 "Driver"]
			["g" 7 "Quantity"]
			["a" 1 "Unknown"]
			["b" 2 "Test"]
			["c" 3 "Master"]
			["d" 4 "Price"]
			["e" 5 "Unknown"]
			["f" 6 "Driver"]
			["g" 7 "Quantity"]
		]
		row-spec		[
			[text red 180x5 font [style: 'bold align: 'right valign: 'middle] para [wrap?: none]]
			[text blue 192x5 #WP para [wrap?: none]]
			[drop-list 130x5 []]
		]
	]
]

ll: ctx-rebgui/layout copy/deep lo
g/redraw ; [13] - enable this for the width to be correct, so this is probably correct behavior. this is disabled, so you can see what the REDRAW does, if you do [8]
display "" ll
do-events